version: '3.1'
services:

  trello-clone-server:
    container_name: trello-clone-server
    build:
      context: .
      dockerfile: Dockerfile
    image: trello-clone-server:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/trello-clone-db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVER.PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_USER=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
